{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "c11n-messaging.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: constellation-messaging
spec:
  replicas: {{ .Values.c11nMessagingRuntime.replicaCount }}
  selector:
    matchLabels:
      app: constellation-messaging
  template:
    metadata:
      labels:
        app: constellation-messaging
    spec:
      imagePullSecrets:
        - name: {{ template "c11n-messagingRegistrySecretName" . }}
      containers:
        - name: c11n-messaging-service
          image: {{ .Values.c11nMessagingRuntime.c11nMessagingImage }}
          imagePullPolicy: {{ .Values.c11nMessagingRuntime.imagePullPolicy }}
          ports:
            - name: c11n-messaging-port
              containerPort: 3000
              protocol: TCP
          env:
            - --max-semi-space-size=1024
            - root=/usr/src/app/environments
            - port=3000
          livenessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /c11n-messaging/v001/healthcheck
              port: 3000
          readinessProbe:
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /c11n-messaging/v001/healthcheck
              port: 3000
          resources:
            {{- toYaml .Values.c11nMessagingRuntime.resources | nindent 12 }}
  {{ end }}
