{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "c11n-messaging.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "c11n-messaging.c11n-messaging-service.labels" . | indent 4 }}
spec:
  type: {{ .Values.c11nMessagingRuntime.serviceType }}
  selector:
{{- include "c11n-messaging.c11n-messaging-service.match-labels" . | indent 4 }}
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 3000
{{ end }}
