{{ if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "c11n-messaging.fullname" . }}-reg-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imageRepositorySecret" . }}
{{ end }}
