---
enabled: true
deployment:
  name: "constellation"
# Cloud provider details. Accepted values are aws or gcp
cloudProvider: aws
# For aws cloud provider enter your acm certificate ARN here.
awsCertificateArn : arn:aws:acm:us-west-2:xxxxx:certificate/xxxxxxx
domainName: helm-test.constellation.pega.io
# Docker repos and tag for image
docker:
    # If using a custom Docker registry, supply the credentials here to pull Docker images.
    registry:
      url: "cirrus-docker.jfrog.io"
      username: cameng2
      password: d8538894e2
    # Docker image information for the Pega docker image, containing the application server.
    constellation:
      image: cirrus-docker.jfrog.io/constellation-appstatic-service/docker-image:1.0.8-20221228123724
logLevel: info
urlPath: /c11n
replicas: 1
livenessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3